---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  require_ansible_omnibus: true
## required for some gem/busser testing
#  require_chef_for_busser: false

platforms:
## FIXME! /bin/bash: ansible-playbook: command not found
##  https://github.com/neillturner/kitchen-ansible/issues/106
  - name: ubuntu-20.04
  - name: ubuntu-18.04
    driver_config:
      network:
        - ["forwarded_port", {guest: 8888, host: 8885}]
  - name: centos-7.4
    driver_config:
      network:
        - ["forwarded_port", {guest: 8888, host: 8887}]

suites:
  - name: default
    run_list:
    attributes:
