---
driver:
  name: lxd_cli
## https://www.stgraber.org/2016/04/13/lxd-2-0-docker-in-lxd-712/
#  profile: "docker"

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
#  - name: ubuntu-12.04
## FIXME!
#TASK [geerlingguy.nginx : Ensure nginx is started and enabled to start at boot.] ***
#       fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Job for nginx.service failed because a timeout was exceeded. See \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}
#  - name: centos-7
## FIXME!
#TASK [geerlingguy.nginx : Ensure nginx is started and enabled to start at boot.] ***
#       fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)\nnginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)\nnginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)\nnginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)\nnginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)\nnginx: [emerg] still could not bind()\n"}
#  - name: centos-6
#  - name: alpine-3.4

suites:
  - name: default
    run_list:
    attributes:
  - name: default-vascan
    run_list:
    includes:
      - ubuntu-16.04
#      - ubuntu-14.04
#      - centos-7
#      - centos-6
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default-vascan/default.yml

