---

- name: apt | jenkins dependencies
  apt: name={{ jenkins_extra_pkg }} state=present
  register: pkg_result
  until: pkg_result is success

- name: Ensure aide config directory exists
  file: dest=/etc/aide/aide.conf.d state=directory mode=0755
- name: add additional aide HIDS configuration
  template: src=99_aide_local_jenkins dest=/etc/aide/aide.conf.d/99_aide_local_jenkins mode=0644
