---

- stat: path={{ jenkins_root }}/jobs/{{ job_name | basename }}
  register: jobdir

- name: load job example {{ job_name }} into jenkins through cli
  shell: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/
    create-job {{ job_name | basename }}
    --username {{ jenkins_admin_username }}
    --password {{ jenkins_admin_password }} < {{ jenkins_root }}/{{ job_name | basename }}.xml
  when: not jobdir.stat.exists

