---

- name: send ufw log to separate file through rsyslog
  template: src=rsyslog-ufw.conf.j2 dest=/etc/rsyslog.d/49-ufw.conf mode=0644
  notify:
    - restart rsyslog

- name: add logrotate configuration for ufw.log
  template: src=logrotate-ufw.j2 dest=/etc/logrotate.d/ufw mode=0644

