---

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_os_family == 'Debian'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: configure git so jenkins can interact w github
  template: "src=gitconfig.j2 dest={{ jenkins_root }}/.gitconfig mode=0644 owner=jenkins group=jenkins backup=yes"
  when: jenkins_git_email is defined

## template task not idempotent. how to change default config, preserve local changes like views. xml module?
#- name: configure jenkins config
#  template:
#    src: jenkins-config.xml.j2
#    dest: "{{ jenkins_root }}/config.xml"
#    mode: '0644'
#    owner: jenkins
#    group: jenkins
#    backup: yes
- include: jenkins-config.yml

- name: configure jenkins smtp server
  template:
    src: hudson.tasks.Mailer.xml.j2
    dest: "{{ jenkins_root }}/hudson.tasks.Mailer.xml"
    mode: '0644'
    owner: jenkins
    group: jenkins
    backup: yes
  when: jenkins_smtphost is defined and jenkins_smtphost

- name: create ssh key for jenkins user
  user:
    name: jenkins
    generate_ssh_key: yes
    ssh_key_comment: "jenkins-key-for-{{ inventory_hostname }}"
    ssh_key_type: "{{ item }}"
  with_items: "{{ jenkins_user_sshkeytypes }}"

- name: check permissions of secrets directory
  file: "dest={{ jenkins_root }}/secrets state=directory mode=0700"

#- debug: var=jenkins_job_examples
- block:
    - name: upload job examples
      template: "src={{ item }} dest={{ jenkins_root }}/{{ item | basename }} mode=0644 backup=yes"
      with_items: "{{ jenkins_job_examples }}"
    - include: "jenkins-create-job.yml job_name={{ item[:-4] }} job_file={{ jenkins_root }}/{{ job_name | basename }}.xml"
      with_items: "{{ jenkins_job_examples }}"
  when: jenkins_job_examples is defined and jenkins_job_examples != []
#- debug: var=jenkins_job_local_examples
- block:
    - include: "jenkins-create-job.yml job_name={{ item[:-4] | basename }} job_file={{ item }}"
      with_items: "{{ jenkins_job_local_examples }}"
  when: jenkins_job_local_examples is defined and jenkins_job_local_examples != []
- block:
    - include: "jenkins-create-view.yml view_name={{ item[:-4] | basename }} view_file={{ item }}"
      with_items: "{{ jenkins_view_local_examples }}"
  when: jenkins_view_local_examples is defined and jenkins_view_local_examples != []

- block:
    - name: Set fact certificate cn
      set_fact:
        certificate_cn: "{{ ansible_fqdn }}"
    - include: certificate-selfsigned.yml
    - name: Set fact certificate key and cert path
      set_fact:
        jenkins_nginx_ssl_key: "{{ ssl_privatedir }}/{{ ansible_fqdn }}.key"
        jenkins_nginx_ssl_cert: "{{ ssl_dir }}/{{ ansible_fqdn }}.crt"
  when: jenkins_public_https and not jenkins_nginx_ssl_cert

- name: set configuration for nginx as reverse proxy
  template: "src=nginx.conf.j2 dest={{ nginx_jenkins_conf }} mode=0644 backup=yes"
  notify:
    - restart nginx
- name: enabled configuration for nginx as reverse proxy
  file: "src={{ nginx_sitedir }}/jenkins dest=/etc/nginx/sites-enabled/jenkins state=link"
  notify:
    - restart nginx
  when: ansible_os_family == 'Debian'
- name: disable default configuration for nginx
  file: dest=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx
  when: ansible_os_family == 'Debian'

- include: jenkins-ssh-auth.xml

- include: monit.yml

- name: Ensure nrpe.d dir exists
  file: dest=/etc/nagios/nrpe.d state=directory mode=0755
- name: add some nrpe commands for monitoring
  template: src=jenkins-nrpe.cfg.j2 dest=/etc/nagios/nrpe.d/jenkins-nrpe.cfg mode=0644 backup=yes


- include: backup-restore.yml

#- include: dashing.yml

- include: firewall-ufw.yml
  when: >
    jenkins_ufw is defined and jenkins_ufw and
    not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")

## we enforce that jenkins is available at the end of the role and it is slow start so...
- meta: flush_handlers
- name: Wait for Jenkins to be available before ending.
  shell: >
    curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/
  register: result
  until: >
    (result.stdout.find("403 Forbidden") != -1) or
    (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  changed_when: false
