---

- name: yum | jenkins dependencies install
  yum: name={{item}} state=present
  with_items:
    - git
    - subversion
    - graphviz

- name: yum | jenkins dependencies - extra
  yum: name={{item}} state=present
  with_items:
    - "{{ jenkins_extra_pkg }}"

# https://access.redhat.com/solutions/2216431 rhel/centos7
- name: yum | ensure latest curl
  yum:
    name: curl
    state: latest

- name: RedHat | install manually python lxml
  pip: name=lxml state=present

- block:
    - name: review nginx.pid location - systemd
      replace: dest=/etc/nginx/nginx.conf regexp='/var/run/nginx.pid' replace='/run/nginx.pid' backup=yes
    - name: ensure nginx.pid link in /var/run
      file: src=/run/nginx.pid dest=/var/run/nginx.pid state=link force=yes
  when: ansible_distribution_release == '7'

