---

- name: yum | jenkins dependencies install
  yum: name={{ jenkins_extra_pkg }} state=present
  register: pkg_result
  until: pkg_result is success

# https://access.redhat.com/solutions/2216431 rhel/centos7
- name: yum | ensure latest curl
  yum:
    name: curl
    state: latest
  register: pkg_result
  until: pkg_result is success

- name: RedHat | install manually python lxml
  pip: name=lxml state=present
  register: pkg_result
  until: pkg_result is success

- block:
    - name: review nginx.pid location - systemd
      replace: dest=/etc/nginx/nginx.conf regexp='/var/run/nginx.pid' replace='/run/nginx.pid' backup=yes
    - name: ensure nginx.pid link in /var/run
      file: src=/run/nginx.pid dest=/var/run/nginx.pid state=link force=yes
  when: ansible_distribution_release == '7'
